# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3991ec6b63ec6be840a7547667faffb3d3d49dc6310aa259cfb42f137dd56614e15c4f958539f4135e7b6b298a09b0877050af304f6d13805aeda898faabc16a

test:
  secret_key_base: f8a22fb8028e16745e2141d20a6c3194ea9bfb8ec6464c3c1d77cc5dfaa2214671846f698b66ae80a1ae0e9e02bf1bf09816e0ab0572c521a0933658466bd12b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
